### ISSUE TITLE
Unhandled Exception: System.Exception: Base resource file was not found. [when running with -recursively option]

### ISSUE THREAD

**Issue by gabrielAnzaldo** [CrocInc/ResxToJson#2]
hi all, 
I have a visual studio 2012 project, and inside it almost 100 resources (*.resx) files, in different files levels; when I apply the -recursively option the error in the title appear.

Detailed error:

Unhandled Exception: System.Exception: Base resource file was not found:
  at Croc.DevTools.ResxToJson.ResxHelper.GetResources(IList`1 inputFiles) in d:
\Work\R-n-D\XFW3_WebClient_tools\ResxToJson\ResxToJson\ResxHelper.cs:line 87
  at Croc.DevTools.ResxToJson.ResxHelper.GetResources(ICollection`1 directories
 Boolean recursive) in d:\Work\R-n-D\XFW3_WebClient_tools\ResxToJson\ResxToJson
ResxHelper.cs:line 118

Does anybody can help me? Thanks!

**Comment by evil-shrike** [comment]
@thelordgabo Hi. Please provide exact cmd-line string which you run the tool with.

**Comment by gabrielAnzaldo** [comment]
hi @evil-shrike this is the cmd-line: ResxToJson.exe -i .\project -dir .\results -format i18next -fallback en -recursively -f

**Comment by gabrielAnzaldo** [comment]
This is the full error message in the console: 
![error](https://cloud.githubusercontent.com/assets/3825673/7588178/6a6d7392-f889-11e4-95c3-93ab55b27167.PNG)

**Comment by evil-shrike** [comment]
@thelordgabo I've created a sample project with the following structure:

```
run.cmd
project/
  1/
    Resources.resx
    Resources.ru.resx
  2/
    3/
      Resources2.resx
      Resources2.ru.resx
```

And it works fine. I'm afraid the tool fails on some particular resource file (not because of `-recursive` flag).
I guess that you have a resx file with culture suffix (like '.fr', '.ru') but without a base file (a file without suffix) beside. Could you check whether this is the case.

**Comment by evil-shrike** [comment]
I added check for that case - ignoring resx files without base file.
@thelordgabo could you try with master version?

**Comment by gabrielAnzaldo** [comment]
ok @evil-shrike i will try master version, give me a moment.

**Comment by gabrielAnzaldo** [comment]
Sorry for the delay, I am novice with .net, @evil-shrike  yes it works! thanks a lot you save me a lot of time!

**Comment by gabrielAnzaldo** [comment]
@evil-shrike I guess I will mark the issue as close right?

**Comment by evil-shrike** [comment]
@thelordgabo Ok, then I'll publish the updated version to nuget.org. Thanks for reporting.
