### ISSUE TITLE
license details are missing

### ISSUE THREAD

**Issue by gabrielAnzaldo** [CrocInc/ResxToJson#3]
hi, I want to use your code, modify and extend it according to my needs, do I have to mention the author in some part?? which is the type of license?

Regards.

**Comment by evil-shrike** [comment]
@thelordgabo thanks for asking. I added the license (MIT). It allows you to do anything you want while including our copyright (see http://choosealicense.com/licenses/mit/ for details).

**Comment by gabrielAnzaldo** [comment]
OK, thanks for the response.
